### ISSUE TITLE
Seeking for the paper

### ISSUE THREAD

**Issue by trumDog** [bluer555/KernelGCN#1]
Hi, I' m very interested in your NeurIPS 2019 work 《Rethinking Kernel Methods for Node Representation Learning on Graphs》,  but it has not been published yet, can you upload a manuscript?

**Comment by garyzhao** [comment]
Hi @trumDog 

Thanks for your interest in our work. Now the paper has been released at:
https://arxiv.org/abs/1910.02548

Best,
Long
